### ISSUE TITLE
How to use the dropdown component in React

### ISSUE THREAD

**Issue by Siddhantsingh1230** [tushargugnani/tailwind-stamps#1]
With working with these dropdowns: https://tailwindcss.5balloons.info/components/dropdown/ 
the components are using x-data sort of attributes (like alpine.js) which is not natively supported by react.
Make the component generalised to be used with any JS lib/framework.

**Comment by tushargugnani** [comment]
@Siddhantsingh1230 This library does not support React / Vue components. This is copy and paste components built using pure tailwindcss or tailwindcss + alpinejs.
